[package]
name = "falcon_proc_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.98", features = [ "full" ] }
quote = { version = "1.0.21" }
proc-macro2 = "1.0.40"
